# Cloud Build configuration para despliegue seguro
steps:
  # Paso 1: Autenticar con Google Cloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'configure-docker']

  # Paso 2: Construir la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/mani-app:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/mani-app:latest',
      '.'
    ]
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

  # Paso 3: Subir la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mani-app:latest']

  # Paso 4: Desplegar a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'mani-app',
      '--image', 'gcr.io/$PROJECT_ID/mani-app:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
    ]

# Configuración de substituciones
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'mani-app'

# Configuración de timeout
timeout: '1200s'

# Imágenes a generar
images:
  - 'gcr.io/$PROJECT_ID/mani-app:latest'

# Opciones adicionales
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
